# include themes/cyberdream-transparent.conf
# include themes/cyberdream.conf
# include themes/star_wars.conf
# include themes/japan.conf
# include themes/alucard.conf
# include themes/atom.conf
# include themes/chalkboard.conf
# include themes/flatland.conf
include themes/tokyonight_night.conf

background_image wallpapers/baby-yoda.jpg
background_image_layout scaled
backgrond_opacity 1
background_tint 0.997
